# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'README.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'scapy[basic]',
  'psutil',
  'ouilookup',
]

extras_require = {
  'yaml': ['PyYAML>=5.1'],
  'dev': ['pytest>=6.0', 'pytest-cov>=2.10'],
}

setuptools.setup(
  name = 'blacktip',
  version = '1.0.0',
  author = 'Nicholas de Jong',
  author_email = 'contact@nicholasdejong.com',
  description = 'A modern network monitoring tool with JSON formatted outputs, exec commands, ARP monitoring, and anomaly detection.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://blacktip.readthedocs.io/',
  license = 'BSD2',
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = extras_require,
  tests_require = ['pytest>=6.0'],
  python_requires = '>=3.6.0,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'blacktip = blacktip.cli.entrypoints:blacktip',
    ]
  },
  cmdclass = {},
  keywords = ['blacktip', 'arp', 'network', 'security', 'monitoring', 'anomaly-detection'],
  classifiers = ['Environment :: Console', 'Intended Audience :: System Administrators', 'Intended Audience :: Information Technology', 'Topic :: System :: Networking :: Monitoring', 'Topic :: Security', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: 3.10', 'Programming Language :: Python :: 3.11', 'License :: OSI Approved :: BSD License'],
  zip_safe = True,
)
